default_context:
  project_name: 'freshword'
  project_slug: 'freshword'
  domain_main: 'freshword.com'
  domain_staging: 'staging.freshword.com'
  docker_swarm_stack_name_main: 'freshword-com'
  docker_swarm_stack_name_staging: 'staging-freshword-com'
  secret_key: 'b17fd2843808a18952c62c053155b45df626bf92afa305859a463509987adb4f'
  first_superuser: 'admin@freshword.com'
  first_superuser_password: '366d216429ed6345280804950d2d629956348a506ec9e4ea8ee0333b1c2fd254'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.freshword.com", "https://staging.freshword.com", "https://freshword.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@freshword.com'
  postgres_password: '814c00c1bdea3a8da184d65deb3645cbec157cda0b18d22a32d8b7a6edc360ff'
  pgadmin_default_user: 'admin@freshword.com'
  pgadmin_default_user_password: 'eaa062d6679311e7db6d8de81cfde851194b6ed23fbd8fd5e821d14a99026b39'
  traefik_constraint_tag: 'freshword.com'
  traefik_constraint_tag_staging: 'staging.freshword.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:366d216429ed6345280804950d2d629956348a506ec9e4ea8ee0333b1c2fd254'
  sentry_dsn: ''
  docker_image_prefix: 'freshword'
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
