import logging

from tenacity import after_log, before_log, retry, stop_after_attempt, wait_fixed

from app.models.db_models import Bible_Book, Bible_Chapter, Bible_Verse

from app.db.session import SessionLocal

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

max_tries = 60 * 5  # 5 minutes
wait_seconds = 1


@retry(
    stop=stop_after_attempt(max_tries),
    wait=wait_fixed(wait_seconds),
    before=before_log(logger, logging.INFO),
    after=after_log(logger, logging.WARN),
)
def init() -> None:
    try:
        db = SessionLocal()
        # Try to create session to check if DB is awake
        db.execute("SELECT 1")
    except Exception as e:
        logger.error(e)
        raise e


def create_books(db: SessionLocal()) -> Bible_Book:
    try:
        books = [
            Bible_Book(title="Genesis", slug="GEN"),
            Bible_Book(title="Exodus", slug="EXO"),
            Bible_Book(title="Leviticus", slug="LEV"),
            Bible_Book(title="Numbers", slug="NUM"),
            Bible_Book(title="Deuteronomy", slug="DEU"),
            Bible_Book(title="Joshua", slug="JOS"),
            Bible_Book(title="Judges", slug="JDG"),
            Bible_Book(title="Ruth", slug="RUT"),
            Bible_Book(title="1 Samuel", slug="1SA"),
            Bible_Book(title="2 Samuel", slug="2SA"),
            Bible_Book(title="1 Kings", slug="1KI"),
            Bible_Book(title="2 Kings", slug="2KI"),
            Bible_Book(title="1 Chronicles", slug="1CH"),
            Bible_Book(title="2 Chronicles", slug="2CH"),
            Bible_Book(title="Ezra", slug="EZR"),
            Bible_Book(title="Nehemiah", slug="NEH"),
            Bible_Book(title="Esther", slug="EST"),
            Bible_Book(title="Job", slug="JOB"),
            Bible_Book(title="Psalms", slug="PSA"),
            Bible_Book(title="Proverbs", slug="PRO"),
            Bible_Book(title="Ecclesiastes", slug="ECC"),
            Bible_Book(title="SongofSongs", slug="SNG"),
            Bible_Book(title="Isaiah", slug="ISA"),
            Bible_Book(title="Jeremiah", slug="JER"),
            Bible_Book(title="Lamentations", slug="LAM"),
            Bible_Book(title="Ezekiel", slug="EZK"),
            Bible_Book(title="Daniel", slug="DAN"),
            Bible_Book(title="Hosea", slug="HOS"),
            Bible_Book(title="Joel", slug="JOL"),
            Bible_Book(title="Amos", slug="AMO"),
            Bible_Book(title="Obadiah", slug="OBA"),
            Bible_Book(title="Jonah", slug="JON"),
            Bible_Book(title="Micah", slug="MIC"),
            Bible_Book(title="Nahum", slug="NAM"),
            Bible_Book(title="Habakkuk", slug="HAB"),
            Bible_Book(title="Zephaniah", slug="ZEP"),
            Bible_Book(title="Haggai", slug="HAG"),
            Bible_Book(title="Zechariah", slug="ZEC"),
            Bible_Book(title="Malachi", slug="MAL"),
            Bible_Book(title="Matthew", slug="MAT"),
            Bible_Book(title="Mark", slug="MRK"),
            Bible_Book(title="Luke", slug="LUK"),
            Bible_Book(title="John", slug="JHN"),
            Bible_Book(title="Acts", slug="ACT"),
            Bible_Book(title="Romans", slug="ROM"),
            Bible_Book(title="1 Corinthians", slug="1CO"),
            Bible_Book(title="2 Corinthians", slug="2CO"),
            Bible_Book(title="Galatians", slug="GAL"),
            Bible_Book(title="Ephesians", slug="EPH"),
            Bible_Book(title="Philippians", slug="PHP"),
            Bible_Book(title="Colossians", slug="COL"),
            Bible_Book(title="1 Thessalonians", slug="1TH"),
            Bible_Book(title="2 Thessalonians", slug="2TH"),
            Bible_Book(title="1 Timothy", slug="1TI"),
            Bible_Book(title="2 Timothy", slug="2TI"),
            Bible_Book(title="Titus", slug="TIT"),
            Bible_Book(title="Philemon", slug="PHM"),
            Bible_Book(title="Hebrews", slug="HEB"),
            Bible_Book(title="James", slug="JAS"),
            Bible_Book(title="1 Peter", slug="1PE"),
            Bible_Book(title="2 Peter", slug="2PE"),
            Bible_Book(title="1 John", slug="1JN"),
            Bible_Book(title="2 John", slug="2JN"),
            Bible_Book(title="3 John", slug="3JN"),
            Bible_Book(title="Jude", slug="JUD"),
            Bible_Book(title="Revelation", slug="REV")
        ]

        db.bulk_save_objects(books)
        db.commit()

        logging.info("Creating books of the bible")

    except:
        logging.error('NOT WORKING')


def create_chapter(db: SessionLocal()) -> Bible_Chapter:
    chapters = [
        Bible_Chapter(title="Genesis 1", book_id=1),
        Bible_Chapter(title="Genesis 2", book_id=1),
        Bible_Chapter(title="Genesis 3", book_id=1),
        Bible_Chapter(title="Genesis 4", book_id=1),
        Bible_Chapter(title="Genesis 5", book_id=1),
        Bible_Chapter(title="Genesis 6", book_id=1),
        Bible_Chapter(title="Genesis 7", book_id=1),
        Bible_Chapter(title="Genesis 8", book_id=1),
        Bible_Chapter(title="Genesis 9", book_id=1),
        Bible_Chapter(title="Genesis 10", book_id=1),
        Bible_Chapter(title="Genesis 11", book_id=1),
        Bible_Chapter(title="Genesis 12", book_id=1),
        Bible_Chapter(title="Genesis 13", book_id=1),
        Bible_Chapter(title="Genesis 14", book_id=1),
        Bible_Chapter(title="Genesis 15", book_id=1),
        Bible_Chapter(title="Genesis 16", book_id=1),
        Bible_Chapter(title="Genesis 17", book_id=1),
        Bible_Chapter(title="Genesis 18", book_id=1),
        Bible_Chapter(title="Genesis 19", book_id=1),
        Bible_Chapter(title="Genesis 20", book_id=1),
        Bible_Chapter(title="Genesis 21", book_id=1),
        Bible_Chapter(title="Genesis 22", book_id=1),
        Bible_Chapter(title="Genesis 23", book_id=1),
        Bible_Chapter(title="Genesis 24", book_id=1),
        Bible_Chapter(title="Genesis 25", book_id=1),
        Bible_Chapter(title="Genesis 26", book_id=1),
        Bible_Chapter(title="Genesis 27", book_id=1),
        Bible_Chapter(title="Genesis 28", book_id=1),
        Bible_Chapter(title="Genesis 29", book_id=1),
        Bible_Chapter(title="Genesis 30", book_id=1),
        Bible_Chapter(title="Genesis 31", book_id=1),
        Bible_Chapter(title="Genesis 32", book_id=1),
        Bible_Chapter(title="Genesis 33", book_id=1),
        Bible_Chapter(title="Genesis 34", book_id=1),
        Bible_Chapter(title="Genesis 35", book_id=1),
        Bible_Chapter(title="Genesis 36", book_id=1),
        Bible_Chapter(title="Genesis 37", book_id=1),
        Bible_Chapter(title="Genesis 38", book_id=1),
        Bible_Chapter(title="Genesis 39", book_id=1),
        Bible_Chapter(title="Genesis 40", book_id=1),
        Bible_Chapter(title="Genesis 41", book_id=1),
        Bible_Chapter(title="Genesis 42", book_id=1),
        Bible_Chapter(title="Genesis 43", book_id=1),
        Bible_Chapter(title="Genesis 44", book_id=1),
        Bible_Chapter(title="Genesis 45", book_id=1),
        Bible_Chapter(title="Genesis 46", book_id=1),
        Bible_Chapter(title="Genesis 47", book_id=1),
        Bible_Chapter(title="Genesis 48", book_id=1),
        Bible_Chapter(title="Genesis 49", book_id=1),
        Bible_Chapter(title="Genesis 50", book_id=1),
        Bible_Chapter(title="Exodus 1", book_id=2),
        Bible_Chapter(title="Exodus 2", book_id=2),
        Bible_Chapter(title="Exodus 3", book_id=2),
        Bible_Chapter(title="Exodus 4", book_id=2),
        Bible_Chapter(title="Exodus 5", book_id=2),
        Bible_Chapter(title="Exodus 6", book_id=2),
        Bible_Chapter(title="Exodus 7", book_id=2),
        Bible_Chapter(title="Exodus 8", book_id=2),
        Bible_Chapter(title="Exodus 9", book_id=2),
        Bible_Chapter(title="Exodus 10", book_id=2),
        Bible_Chapter(title="Exodus 11", book_id=2),
        Bible_Chapter(title="Exodus 12", book_id=2),
        Bible_Chapter(title="Exodus 13", book_id=2),
        Bible_Chapter(title="Exodus 14", book_id=2),
        Bible_Chapter(title="Exodus 15", book_id=2),
        Bible_Chapter(title="Exodus 16", book_id=2),
        Bible_Chapter(title="Exodus 17", book_id=2),
        Bible_Chapter(title="Exodus 18", book_id=2),
        Bible_Chapter(title="Exodus 19", book_id=2),
        Bible_Chapter(title="Exodus 20", book_id=2),
        Bible_Chapter(title="Exodus 16", book_id=2),
        Bible_Chapter(title="Exodus 17", book_id=2),
        Bible_Chapter(title="Exodus 18", book_id=2),
        Bible_Chapter(title="Exodus 19", book_id=2),
        Bible_Chapter(title="Exodus 20", book_id=2),
        Bible_Chapter(title="Exodus 21", book_id=2),
        Bible_Chapter(title="Exodus 22", book_id=2),
        Bible_Chapter(title="Exodus 23", book_id=2),
        Bible_Chapter(title="Exodus 24", book_id=2),
        Bible_Chapter(title="Exodus 25", book_id=2),
        Bible_Chapter(title="Exodus 26", book_id=2),
        Bible_Chapter(title="Exodus 27", book_id=2),
        Bible_Chapter(title="Exodus 28", book_id=2),
        Bible_Chapter(title="Exodus 29", book_id=2),
        Bible_Chapter(title="Exodus 30", book_id=2),
        Bible_Chapter(title="Exodus 31", book_id=2),
        Bible_Chapter(title="Exodus 32", book_id=2),
        Bible_Chapter(title="Exodus 33", book_id=2),
        Bible_Chapter(title="Exodus 34", book_id=2),
        Bible_Chapter(title="Exodus 35", book_id=2),
        Bible_Chapter(title="Exodus 36", book_id=2),
        Bible_Chapter(title="Exodus 37", book_id=2),
        Bible_Chapter(title="Exodus 38", book_id=2),
        Bible_Chapter(title="Exodus 39", book_id=2),
        Bible_Chapter(title="Exodus 40", book_id=2),
        Bible_Chapter(title="Leviticus 1", book_id=3),
        Bible_Chapter(title="Leviticus 2", book_id=3),
        Bible_Chapter(title="Leviticus 3 Instructions for Peace Sacrifices", book_id=3),
        Bible_Chapter(
            title="Leviticus 4 Instructions for Unintentional Sins", book_id=3),
        Bible_Chapter(title="Leviticus 5", book_id=3),
        Bible_Chapter(title="Leviticus 6", book_id=3),
        Bible_Chapter(title="Leviticus 7", book_id=3),
        Bible_Chapter(title="Leviticus 8", book_id=3),
        Bible_Chapter(title="Leviticus 9", book_id=3),
        Bible_Chapter(title="Leviticus 10", book_id=3),
        Bible_Chapter(title="Leviticus 11", book_id=3),
        Bible_Chapter(title="Leviticus 12", book_id=3),
        Bible_Chapter(title="Leviticus 13", book_id=3),
        Bible_Chapter(title="Leviticus 14", book_id=3),
        Bible_Chapter(title="Leviticus 15", book_id=3),
        Bible_Chapter(title="Leviticus 16", book_id=3),
        Bible_Chapter(title="Leviticus 17", book_id=3),
        Bible_Chapter(title="Leviticus 18", book_id=3),
        Bible_Chapter(title="Leviticus 19", book_id=3),
        Bible_Chapter(title="Leviticus 20", book_id=3),
        Bible_Chapter(title="Leviticus 21", book_id=3),
        Bible_Chapter(title="Leviticus 22", book_id=3),
        Bible_Chapter(title="Leviticus 23", book_id=3),
        Bible_Chapter(title="Leviticus 24", book_id=3),
        Bible_Chapter(title="Leviticus 25", book_id=3),
        Bible_Chapter(title="Leviticus 26", book_id=3),
        Bible_Chapter(title="Leviticus 27", book_id=3),
        Bible_Chapter(title="Numbers 1", book_id=4),
        Bible_Chapter(title="Numbers 2", book_id=4),
        Bible_Chapter(title="Numbers 3", book_id=4),
        Bible_Chapter(title="Numbers 4", book_id=4),
        Bible_Chapter(title="Numbers 5", book_id=4),
        Bible_Chapter(title="Numbers 6", book_id=4),
        Bible_Chapter(title="Numbers 7", book_id=4),
        Bible_Chapter(title="Numbers 8", book_id=4),
        Bible_Chapter(title="Numbers 9", book_id=4),
        Bible_Chapter(title="Numbers 10", book_id=4),
        Bible_Chapter(title="Numbers 11", book_id=4),
        Bible_Chapter(title="Numbers 12", book_id=4),
        Bible_Chapter(title="Numbers 13", book_id=4),
        Bible_Chapter(title="Numbers 14", book_id=4),
        Bible_Chapter(title="Numbers 15", book_id=4),
        Bible_Chapter(title="Numbers 16", book_id=4),
        Bible_Chapter(title="Numbers 17", book_id=4),
        Bible_Chapter(title="Numbers 18", book_id=4),
        Bible_Chapter(title="Numbers 19", book_id=4),
        Bible_Chapter(title="Numbers 20", book_id=4),
        Bible_Chapter(title="Numbers 21", book_id=4),
        Bible_Chapter(title="Numbers 22", book_id=4),
        Bible_Chapter(title="Numbers 23", book_id=4),
        Bible_Chapter(title="Numbers 24", book_id=4),
        Bible_Chapter(title="Numbers 25", book_id=4),
        Bible_Chapter(title="Numbers 26", book_id=4),
        Bible_Chapter(title="Numbers 27", book_id=4),
        Bible_Chapter(title="Numbers 28", book_id=4),
        Bible_Chapter(title="Numbers 29", book_id=4),
        Bible_Chapter(title="Numbers 30", book_id=4),
        Bible_Chapter(title="Numbers 31", book_id=4),
        Bible_Chapter(title="Numbers 32", book_id=4),
        Bible_Chapter(title="Numbers 33", book_id=4),
        Bible_Chapter(title="Numbers 34", book_id=4),
        Bible_Chapter(title="Numbers 35", book_id=4),
        Bible_Chapter(title="Numbers 36", book_id=4),
        Bible_Chapter(title="Deuteronomy 1", book_id=5),
        Bible_Chapter(title="Deuteronomy 2", book_id=5),
        Bible_Chapter(title="Deuteronomy 3", book_id=5),
        Bible_Chapter(title="Deuteronomy 4", book_id=5),
        Bible_Chapter(title="Deuteronomy 5", book_id=5),
        Bible_Chapter(title="Deuteronomy 6", book_id=5),
        Bible_Chapter(title="Deuteronomy 7", book_id=5),
        Bible_Chapter(title="Deuteronomy 8", book_id=5),
        Bible_Chapter(title="Deuteronomy 9", book_id=5),
        Bible_Chapter(title="Deuteronomy 10", book_id=5),
        Bible_Chapter(title="Deuteronomy 11", book_id=5),
        Bible_Chapter(title="Deuteronomy 12", book_id=5),
        Bible_Chapter(title="Deuteronomy 13", book_id=5),
        Bible_Chapter(title="Deuteronomy 14", book_id=5),
        Bible_Chapter(title="Deuteronomy 15", book_id=5),
        Bible_Chapter(title="Deuteronomy 16", book_id=5),
        Bible_Chapter(title="Deuteronomy 17", book_id=5),
        Bible_Chapter(title="Deuteronomy 18", book_id=5),
        Bible_Chapter(title="Deuteronomy 19", book_id=5),
        Bible_Chapter(title="Deuteronomy 20", book_id=5),
        Bible_Chapter(title="Deuteronomy 21", book_id=5),
        Bible_Chapter(title="Deuteronomy 22", book_id=5),
        Bible_Chapter(title="Deuteronomy 23", book_id=5),
        Bible_Chapter(title="Deuteronomy 24", book_id=5),
        Bible_Chapter(title="Deuteronomy 25", book_id=5),
        Bible_Chapter(title="Deuteronomy 26", book_id=5),
        Bible_Chapter(title="Deuteronomy 27", book_id=5),
        Bible_Chapter(title="Deuteronomy 28", book_id=5),
        Bible_Chapter(title="Deuteronomy 29", book_id=5),
        Bible_Chapter(title="Deuteronomy 30", book_id=5),
        Bible_Chapter(title="Deuteronomy 31", book_id=5),
        Bible_Chapter(title="Deuteronomy 32", book_id=5),
        Bible_Chapter(title="Deuteronomy 33", book_id=5),
        Bible_Chapter(title="Deuteronomy 34", book_id=5),
        Bible_Chapter(title="Joshua 1", book_id=6),
        Bible_Chapter(title="Joshua 2", book_id=6),
        Bible_Chapter(title="Joshua 3", book_id=6),
        Bible_Chapter(title="Joshua 4", book_id=6),
        Bible_Chapter(title="Joshua 5", book_id=6),
        Bible_Chapter(title="Joshua 6", book_id=6),
        Bible_Chapter(title="Joshua 7", book_id=6),
        Bible_Chapter(title="Joshua 8", book_id=6),
        Bible_Chapter(title="Joshua 9", book_id=6),
        Bible_Chapter(title="Joshua 10", book_id=6),
        Bible_Chapter(title="Joshua 11", book_id=6),
        Bible_Chapter(title="Joshua 12", book_id=6),
        Bible_Chapter(title="Joshua 13", book_id=6),
        Bible_Chapter(title="Joshua 14", book_id=6),
        Bible_Chapter(title="Joshua 15", book_id=6),
        Bible_Chapter(title="Joshua 16", book_id=6),
        Bible_Chapter(title="Joshua 17", book_id=6),
        Bible_Chapter(title="Joshua 18", book_id=6),
        Bible_Chapter(title="Joshua 19", book_id=6),
        Bible_Chapter(title="Joshua 20", book_id=6),
        Bible_Chapter(title="Joshua 21", book_id=6),
        Bible_Chapter(title="Joshua 22", book_id=6),
        Bible_Chapter(title="Joshua 23", book_id=6),
        Bible_Chapter(title="Joshua 24", book_id=6),
        Bible_Chapter(title="Judges 1", book_id=7),
        Bible_Chapter(title="Judges 2", book_id=7),
        Bible_Chapter(title="Judges 3", book_id=7),
        Bible_Chapter(title="Judges 4", book_id=7),
        Bible_Chapter(title="Judges 5", book_id=7),
        Bible_Chapter(title="Judges 6", book_id=7),
        Bible_Chapter(title="Judges 7", book_id=7),
        Bible_Chapter(title="Judges 8", book_id=7),
        Bible_Chapter(title="Judges 9", book_id=7),
        Bible_Chapter(title="Judges 10", book_id=7),
        Bible_Chapter(title="Judges 11", book_id=7),
        Bible_Chapter(title="Judges 12", book_id=7),
        Bible_Chapter(title="Judges 13", book_id=7),
        Bible_Chapter(title="Judges 14", book_id=7),
        Bible_Chapter(title="Judges 15", book_id=7),
        Bible_Chapter(title="Judges 16", book_id=7),
        Bible_Chapter(title="Judges 17", book_id=7),
        Bible_Chapter(title="Judges 18", book_id=7),
        Bible_Chapter(title="Judges 19", book_id=7),
        Bible_Chapter(title="Judges 20", book_id=7),
        Bible_Chapter(title="Judges 21", book_id=7),
        Bible_Chapter(title="Ruth 1", book_id=8),
        Bible_Chapter(title="Ruth 2", book_id=8),
        Bible_Chapter(title="Ruth 3", book_id=8),
        Bible_Chapter(title="Ruth 4", book_id=8),
        Bible_Chapter(title="1 Samuel 1", book_id=9),
        Bible_Chapter(title="1 Samuel 2", book_id=9),
        Bible_Chapter(title="1 Samuel 3", book_id=9),
        Bible_Chapter(title="1 Samuel 4", book_id=9),
        Bible_Chapter(title="1 Samuel 5", book_id=9),
        Bible_Chapter(title="1 Samuel 6", book_id=9),
        Bible_Chapter(title="1 Samuel 7", book_id=9),
        Bible_Chapter(title="1 Samuel 8", book_id=9),
        Bible_Chapter(title="1 Samuel 9", book_id=9),
        Bible_Chapter(title="1 Samuel 10", book_id=9),
        Bible_Chapter(title="1 Samuel 11", book_id=9),
        Bible_Chapter(title="1 Samuel 12", book_id=9),
        Bible_Chapter(title="1 Samuel 13", book_id=9),
        Bible_Chapter(title="1 Samuel 14", book_id=9),
        Bible_Chapter(title="1 Samuel 15", book_id=9),
        Bible_Chapter(title="1 Samuel 16", book_id=9),
        Bible_Chapter(title="1 Samuel 17", book_id=9),
        Bible_Chapter(title="1 Samuel 18", book_id=9),
        Bible_Chapter(title="1 Samuel 19", book_id=9),
        Bible_Chapter(title="1 Samuel 20", book_id=9),
        Bible_Chapter(title="1 Samuel 21", book_id=9),
        Bible_Chapter(title="1 Samuel 22", book_id=9),
        Bible_Chapter(title="1 Samuel 23", book_id=9),
        Bible_Chapter(title="1 Samuel 24", book_id=9),
        Bible_Chapter(title="1 Samuel 25", book_id=9),
        Bible_Chapter(title="1 Samuel 26", book_id=9),
        Bible_Chapter(title="1 Samuel 27", book_id=9),
        Bible_Chapter(title="1 Samuel 28", book_id=9),
        Bible_Chapter(title="1 Samuel 29", book_id=9),
        Bible_Chapter(title="1 Samuel 30", book_id=9),
        Bible_Chapter(title="1 Samuel 31", book_id=9),
        Bible_Chapter(title="2 Samuel 1", book_id=10),
        Bible_Chapter(title="2 Samuel 2", book_id=10),
        Bible_Chapter(title="2 Samuel 3", book_id=10),
        Bible_Chapter(title="2 Samuel 4", book_id=10),
        Bible_Chapter(title="2 Samuel 5", book_id=10),
        Bible_Chapter(title="2 Samuel 6", book_id=10),
        Bible_Chapter(title="2 Samuel 7", book_id=10),
        Bible_Chapter(title="2 Samuel 8", book_id=10),
        Bible_Chapter(title="2 Samuel 9", book_id=10),
        Bible_Chapter(title="2 Samuel 10", book_id=10),
        Bible_Chapter(title="2 Samuel 11", book_id=10),
        Bible_Chapter(title="2 Samuel 12", book_id=10),
        Bible_Chapter(title="2 Samuel 13", book_id=10),
        Bible_Chapter(title="2 Samuel 14", book_id=10),
        Bible_Chapter(title="2 Samuel 15", book_id=10),
        Bible_Chapter(title="2 Samuel 16", book_id=10),
        Bible_Chapter(title="2 Samuel 17", book_id=10),
        Bible_Chapter(title="2 Samuel 18", book_id=10),
        Bible_Chapter(title="2 Samuel 19", book_id=10),
        Bible_Chapter(title="2 Samuel 20", book_id=10),
        Bible_Chapter(title="2 Samuel 21", book_id=10),
        Bible_Chapter(title="2 Samuel 22", book_id=10),
        Bible_Chapter(title="2 Samuel 23", book_id=10),
        Bible_Chapter(title="2 Samuel 24", book_id=10),
        Bible_Chapter(title="1 Kings 1", book_id=11),
        Bible_Chapter(title="1 Kings 2", book_id=11),
        Bible_Chapter(title="1 Kings 3", book_id=11),
        Bible_Chapter(title="1 Kings 4", book_id=11),
        Bible_Chapter(title="1 Kings 5", book_id=11),
        Bible_Chapter(title="1 Kings 6", book_id=11),
        Bible_Chapter(title="1 Kings 7", book_id=11),
        Bible_Chapter(title="1 Kings 8", book_id=11),
        Bible_Chapter(title="1 Kings 9", book_id=11),
        Bible_Chapter(title="1 Kings 10", book_id=11),
        Bible_Chapter(title="1 Kings 11", book_id=11),
        Bible_Chapter(title="1 Kings 12", book_id=11),
        Bible_Chapter(title="1 Kings 13", book_id=11),
        Bible_Chapter(title="1 Kings 14", book_id=11),
        Bible_Chapter(title="1 Kings 15", book_id=11),
        Bible_Chapter(title="1 Kings 16", book_id=11),
        Bible_Chapter(title="1 Kings 17", book_id=11),
        Bible_Chapter(title="1 Kings 18", book_id=11),
        Bible_Chapter(title="1 Kings 19", book_id=11),
        Bible_Chapter(title="1 Kings 20", book_id=11),
        Bible_Chapter(title="1 Kings 21", book_id=11),
        Bible_Chapter(title="1 Kings 22", book_id=11),
        Bible_Chapter(title="2 Kings 1", book_id=12),
        Bible_Chapter(title="2 Kings 2", book_id=12),
        Bible_Chapter(title="2 Kings 3", book_id=12),
        Bible_Chapter(title="2 Kings 4", book_id=12),
        Bible_Chapter(title="2 Kings 5", book_id=12),
        Bible_Chapter(title="2 Kings 6", book_id=12),
        Bible_Chapter(title="2 Kings 7", book_id=12),
        Bible_Chapter(title="2 Kings 8", book_id=12),
        Bible_Chapter(title="2 Kings 9", book_id=12),
        Bible_Chapter(title="2 Kings 10", book_id=12),
        Bible_Chapter(title="2 Kings 11", book_id=12),
        Bible_Chapter(title="2 Kings 12", book_id=12),
        Bible_Chapter(title="2 Kings 13", book_id=12),
        Bible_Chapter(title="2 Kings 14", book_id=12),
        Bible_Chapter(title="2 Kings 15", book_id=12),
        Bible_Chapter(title="2 Kings 16", book_id=12),
        Bible_Chapter(title="2 Kings 17", book_id=12),
        Bible_Chapter(title="2 Kings 18", book_id=12),
        Bible_Chapter(title="2 Kings 19", book_id=12),
        Bible_Chapter(title="2 Kings 20", book_id=12),
        Bible_Chapter(title="2 Kings 21", book_id=12),
        Bible_Chapter(title="2 Kings 22", book_id=12),
        Bible_Chapter(title="2 Kings 23", book_id=12),
        Bible_Chapter(title="2 Kings 24", book_id=12),
        Bible_Chapter(title="2 Kings 25", book_id=12),
        Bible_Chapter(title="1 Chronicles 1", book_id=13),
        Bible_Chapter(title="1 Chronicles 2", book_id=13),
        Bible_Chapter(title="1 Chronicles 3", book_id=13),
        Bible_Chapter(title="1 Chronicles 4", book_id=13),
        Bible_Chapter(title="1 Chronicles 5", book_id=13),
        Bible_Chapter(title="1 Chronicles 6", book_id=13),
        Bible_Chapter(title="1 Chronicles 7", book_id=13),
        Bible_Chapter(title="1 Chronicles 8", book_id=13),
        Bible_Chapter(title="1 Chronicles 9", book_id=13),
        Bible_Chapter(title="1 Chronicles 10", book_id=13),
        Bible_Chapter(title="1 Chronicles 11", book_id=13),
        Bible_Chapter(title="1 Chronicles 12", book_id=13),
        Bible_Chapter(title="1 Chronicles 13", book_id=13),
        Bible_Chapter(title="1 Chronicles 14", book_id=13),
        Bible_Chapter(title="1 Chronicles 15", book_id=13),
        Bible_Chapter(title="1 Chronicles 16", book_id=13),
        Bible_Chapter(title="1 Chronicles 17", book_id=13),
        Bible_Chapter(title="1 Chronicles 18", book_id=13),
        Bible_Chapter(title="1 Chronicles 19", book_id=13),
        Bible_Chapter(title="1 Chronicles 20", book_id=13),
        Bible_Chapter(title="1 Chronicles 21", book_id=13),
        Bible_Chapter(title="1 Chronicles 22", book_id=13),
        Bible_Chapter(title="1 Chronicles 23", book_id=13),
        Bible_Chapter(title="1 Chronicles 24", book_id=13),
        Bible_Chapter(title="1 Chronicles 25", book_id=13),
        Bible_Chapter(title="1 Chronicles 26", book_id=13),
        Bible_Chapter(title="1 Chronicles 27", book_id=13),
        Bible_Chapter(title="1 Chronicles 28", book_id=13),
        Bible_Chapter(title="1 Chronicles 29", book_id=13),
        Bible_Chapter(title="2 Chronicles 1", book_id=14),
        Bible_Chapter(title="2 Chronicles 2", book_id=14),
        Bible_Chapter(title="2 Chronicles 3", book_id=14),
        Bible_Chapter(title="2 Chronicles 4", book_id=14),
        Bible_Chapter(title="2 Chronicles 5", book_id=14),
        Bible_Chapter(title="2 Chronicles 6", book_id=14),
        Bible_Chapter(title="2 Chronicles 7", book_id=14),
        Bible_Chapter(title="2 Chronicles 8", book_id=14),
        Bible_Chapter(title="2 Chronicles 9", book_id=14),
        Bible_Chapter(title="2 Chronicles 10", book_id=14),
        Bible_Chapter(title="2 Chronicles 11", book_id=14),
        Bible_Chapter(title="2 Chronicles 12", book_id=14),
        Bible_Chapter(title="2 Chronicles 13", book_id=14),
        Bible_Chapter(title="2 Chronicles 14", book_id=14),
        Bible_Chapter(title="2 Chronicles 15", book_id=14),
        Bible_Chapter(title="2 Chronicles 16", book_id=14),
        Bible_Chapter(title="2 Chronicles 17", book_id=14),
        Bible_Chapter(title="2 Chronicles 18", book_id=14),
        Bible_Chapter(title="2 Chronicles 19", book_id=14),
        Bible_Chapter(title="2 Chronicles 20", book_id=14),
        Bible_Chapter(title="2 Chronicles 21", book_id=14),
        Bible_Chapter(title="2 Chronicles 22", book_id=14),
        Bible_Chapter(title="2 Chronicles 23", book_id=14),
        Bible_Chapter(title="2 Chronicles 24", book_id=14),
        Bible_Chapter(title="2 Chronicles 25", book_id=14),
        Bible_Chapter(title="2 Chronicles 26", book_id=14),
        Bible_Chapter(title="2 Chronicles 27", book_id=14),
        Bible_Chapter(title="2 Chronicles 28", book_id=14),
        Bible_Chapter(title="2 Chronicles 29", book_id=14),
        Bible_Chapter(title="2 Chronicles 30", book_id=14),
        Bible_Chapter(title="2 Chronicles 31", book_id=14),
        Bible_Chapter(title="2 Chronicles 32", book_id=14),
        Bible_Chapter(title="2 Chronicles 33", book_id=14),
        Bible_Chapter(title="2 Chronicles 34", book_id=14),
        Bible_Chapter(title="2 Chronicles 35", book_id=14),
        Bible_Chapter(title="2 Chronicles 36", book_id=14),
        Bible_Chapter(title="Ezra 1", book_id=15),
        Bible_Chapter(title="Ezra 2", book_id=15),
        Bible_Chapter(title="Ezra 3", book_id=15),
        Bible_Chapter(title="Ezra 4", book_id=15),
        Bible_Chapter(title="Ezra 5", book_id=15),
        Bible_Chapter(title="Ezra 6", book_id=15),
        Bible_Chapter(title="Ezra 7", book_id=15),
        Bible_Chapter(title="Ezra 8", book_id=15),
        Bible_Chapter(title="Ezra 9", book_id=15),
        Bible_Chapter(title="Ezra 10", book_id=15),
        Bible_Chapter(title="Nehemiah 1", book_id=16),
        Bible_Chapter(title="Nehemiah 2", book_id=16),
        Bible_Chapter(title="Nehemiah 3", book_id=16),
        Bible_Chapter(title="Nehemiah 4", book_id=16),
        Bible_Chapter(title="Nehemiah 5", book_id=16),
        Bible_Chapter(title="Nehemiah 6", book_id=16),
        Bible_Chapter(title="Nehemiah 7", book_id=16),
        Bible_Chapter(title="Nehemiah 8", book_id=16),
        Bible_Chapter(title="Nehemiah 9", book_id=16),
        Bible_Chapter(title="Nehemiah 10", book_id=16),
        Bible_Chapter(title="Nehemiah 11", book_id=16),
        Bible_Chapter(title="Nehemiah 12", book_id=16),
        Bible_Chapter(title="Nehemiah 13", book_id=16),
        Bible_Chapter(title="Esther 1", book_id=17),
        Bible_Chapter(title="Esther 2", book_id=17),
        Bible_Chapter(title="Esther 3", book_id=17),
        Bible_Chapter(title="Esther 4", book_id=17),
        Bible_Chapter(title="Esther 5", book_id=17),
        Bible_Chapter(title="Esther 6", book_id=17),
        Bible_Chapter(title="Esther 7", book_id=17),
        Bible_Chapter(title="Esther 8", book_id=17),
        Bible_Chapter(title="Esther 9", book_id=17),
        Bible_Chapter(title="Esther 10", book_id=17),
        Bible_Chapter(title="Job 1", book_id=18),
        Bible_Chapter(title="Job 2", book_id=18),
        Bible_Chapter(title="Job 3", book_id=18),
        Bible_Chapter(title="Job 4", book_id=18),
        Bible_Chapter(title="Job 5", book_id=18),
        Bible_Chapter(title="Job 6", book_id=18),
        Bible_Chapter(title="Job 7", book_id=18),
        Bible_Chapter(title="Job 8", book_id=18),
        Bible_Chapter(title="Job 9", book_id=18),
        Bible_Chapter(title="Job 10", book_id=18),
        Bible_Chapter(title="Job 11", book_id=18),
        Bible_Chapter(title="Job 12", book_id=18),
        Bible_Chapter(title="Job 13", book_id=18),
        Bible_Chapter(title="Job 14", book_id=18),
        Bible_Chapter(title="Job 15", book_id=18),
        Bible_Chapter(title="Job 16", book_id=18),
        Bible_Chapter(title="Job 17", book_id=18),
        Bible_Chapter(title="Job 18", book_id=18),
        Bible_Chapter(title="Job 19", book_id=18),
        Bible_Chapter(title="Job 20", book_id=18),
        Bible_Chapter(title="Job 21", book_id=18),
        Bible_Chapter(title="Job 22", book_id=18),
        Bible_Chapter(title="Job 23", book_id=18),
        Bible_Chapter(title="Job 24", book_id=18),
        Bible_Chapter(title="Job 25", book_id=18),
        Bible_Chapter(title="Job 26", book_id=18),
        Bible_Chapter(title="Job 27", book_id=18),
        Bible_Chapter(title="Job 28", book_id=18),
        Bible_Chapter(title="Job 29", book_id=18),
        Bible_Chapter(title="Job 30", book_id=18),
        Bible_Chapter(title="Job 31", book_id=18),
        Bible_Chapter(title="Job 32", book_id=18),
        Bible_Chapter(title="Job 33", book_id=18),
        Bible_Chapter(title="Job 34", book_id=18),
        Bible_Chapter(title="Job 35", book_id=18),
        Bible_Chapter(title="Job 36", book_id=18),
        Bible_Chapter(title="Job 37", book_id=18),
        Bible_Chapter(title="Job 38", book_id=18),
        Bible_Chapter(title="Job 39", book_id=18),
        Bible_Chapter(title="Job 40", book_id=18),
        Bible_Chapter(title="Job 41", book_id=18),
        Bible_Chapter(title="Job 42", book_id=18),
        Bible_Chapter(title="Psalms 1", book_id=19),
        Bible_Chapter(title="Psalms 2", book_id=19),
        Bible_Chapter(title="Psalms 3", book_id=19),
        Bible_Chapter(title="Psalms 4", book_id=19),
        Bible_Chapter(title="Psalms 5", book_id=19),
        Bible_Chapter(title="Psalms 6", book_id=19),
        Bible_Chapter(title="Psalms 7", book_id=19),
        Bible_Chapter(title="Psalms 8", book_id=19),
        Bible_Chapter(title="Psalms 21", book_id=19),
        Bible_Chapter(title="Psalms 22", book_id=19),
        Bible_Chapter(title="Psalms 23", book_id=19),
        Bible_Chapter(title="Psalms 24", book_id=19),
        Bible_Chapter(title="Psalms 25", book_id=19),
        Bible_Chapter(title="Psalms 26", book_id=19),
        Bible_Chapter(title="Psalms 27", book_id=19),
        Bible_Chapter(title="Psalms 28", book_id=19),
        Bible_Chapter(title="Psalms 29", book_id=19),
        Bible_Chapter(title="Psalms 30", book_id=19),
        Bible_Chapter(title="Psalms 31", book_id=19),
        Bible_Chapter(title="Psalms 32", book_id=19),
        Bible_Chapter(title="Psalms 33", book_id=19),
        Bible_Chapter(title="Psalms 34", book_id=19),
        Bible_Chapter(title="Psalms 35", book_id=19),
        Bible_Chapter(title="Psalms 36", book_id=19),
        Bible_Chapter(title="Psalms 38", book_id=19),
        Bible_Chapter(title="Psalms 39", book_id=19),
        Bible_Chapter(title="Psalms 40", book_id=19),
        Bible_Chapter(title="Psalms 41", book_id=19),
        Bible_Chapter(title="Psalms 42", book_id=19),
        Bible_Chapter(title="Psalms 43", book_id=19),
        Bible_Chapter(title="Psalms 44", book_id=19),
        Bible_Chapter(title="Psalms 45", book_id=19),
        Bible_Chapter(title="Psalms 46", book_id=19),
        Bible_Chapter(title="Psalms 47", book_id=19),
        Bible_Chapter(title="Psalms 48", book_id=19),
        Bible_Chapter(title="Psalms 49", book_id=19),
        Bible_Chapter(title="Psalms 50", book_id=19),
        Bible_Chapter(title="Psalms 51", book_id=19),
        Bible_Chapter(title="Psalms 52", book_id=19),
        Bible_Chapter(title="Psalms 53", book_id=19),
        Bible_Chapter(title="Psalms 54", book_id=19),
        Bible_Chapter(title="Psalms 55", book_id=19),
        Bible_Chapter(title="Psalms 56", book_id=19),
        Bible_Chapter(title="Psalms 57", book_id=19),
        Bible_Chapter(title="Psalms 58", book_id=19),
        Bible_Chapter(title="Psalms 59", book_id=19),
        Bible_Chapter(title="Psalms 60", book_id=19),
        Bible_Chapter(title="Psalms 61", book_id=19),
        Bible_Chapter(title="Psalms 62", book_id=19),
        Bible_Chapter(title="Psalms 63", book_id=19),
        Bible_Chapter(title="Psalms 64", book_id=19),
        Bible_Chapter(title="Psalms 65", book_id=19),
        Bible_Chapter(title="Psalms 66", book_id=19),
        Bible_Chapter(title="Psalms 67", book_id=19),
        Bible_Chapter(title="Psalms 68", book_id=19),
        Bible_Chapter(title="Psalms 69", book_id=19),
        Bible_Chapter(title="Psalms 70", book_id=19),
        Bible_Chapter(title="Psalms 71", book_id=19),
        Bible_Chapter(title="Psalms 72", book_id=19),
        Bible_Chapter(title="Psalms 73", book_id=19),
        Bible_Chapter(title="Psalms 74", book_id=19),
        Bible_Chapter(title="Psalms 75", book_id=19),
        Bible_Chapter(title="Psalms 76", book_id=19),
        Bible_Chapter(title="Psalms 77", book_id=19),
        Bible_Chapter(title="Psalms 78", book_id=19),
        Bible_Chapter(title="Psalms 79", book_id=19),
        Bible_Chapter(title="Psalms 80", book_id=19),
        Bible_Chapter(title="Psalms 81", book_id=19),
        Bible_Chapter(title="Psalms 82", book_id=19),
        Bible_Chapter(title="Psalms 83", book_id=19),
        Bible_Chapter(title="Psalms 84", book_id=19),
        Bible_Chapter(title="Psalms 85", book_id=19),
        Bible_Chapter(title="Psalms 86", book_id=19),
        Bible_Chapter(title="Psalms 87", book_id=19),
        Bible_Chapter(title="Psalms 88", book_id=19),
        Bible_Chapter(title="Psalms 89", book_id=19),
        Bible_Chapter(title="Psalms 90", book_id=19),
        Bible_Chapter(title="Psalms 91", book_id=19),
        Bible_Chapter(title="Psalms 92", book_id=19),
        Bible_Chapter(title="Psalms 93", book_id=19),
        Bible_Chapter(title="Psalms 94", book_id=19),
        Bible_Chapter(title="Psalms 95", book_id=19),
        Bible_Chapter(title="Psalms 96", book_id=19),
        Bible_Chapter(title="Psalms 97", book_id=19),
        Bible_Chapter(title="Psalms 98", book_id=19),
        Bible_Chapter(title="Psalms 99", book_id=19),
        Bible_Chapter(title="Psalms 100", book_id=19),
        Bible_Chapter(title="Psalms 101", book_id=19),
        Bible_Chapter(title="Psalms 102", book_id=19),
        Bible_Chapter(title="Psalms 103", book_id=19),
        Bible_Chapter(title="Psalms 104", book_id=19),
        Bible_Chapter(title="Psalms 105", book_id=19),
        Bible_Chapter(title="Psalms 106", book_id=19),
        Bible_Chapter(title="Psalms 107", book_id=19),
        Bible_Chapter(title="Psalms 108", book_id=19),
        Bible_Chapter(title="Psalms 109", book_id=19),
        Bible_Chapter(title="Psalms 110", book_id=19),
        Bible_Chapter(title="Psalms 111", book_id=19),
        Bible_Chapter(title="Psalms 112", book_id=19),
        Bible_Chapter(title="Psalms 113", book_id=19),
        Bible_Chapter(title="Psalms 114", book_id=19),
        Bible_Chapter(title="Psalms 115", book_id=19),
        Bible_Chapter(title="Psalms 116", book_id=19),
        Bible_Chapter(title="Psalms 117", book_id=19),
        Bible_Chapter(title="Psalms 118", book_id=19),
        Bible_Chapter(title="Psalms 119", book_id=19),
        Bible_Chapter(title="Psalms 120", book_id=19),
        Bible_Chapter(title="Psalms 121", book_id=19),
        Bible_Chapter(title="Psalms 122", book_id=19),
        Bible_Chapter(title="Psalms 123", book_id=19),
        Bible_Chapter(title="Psalms 124", book_id=19),
        Bible_Chapter(title="Psalms 125", book_id=19),
        Bible_Chapter(title="Psalms 126", book_id=19),
        Bible_Chapter(title="Psalms 127", book_id=19),
        Bible_Chapter(title="Psalms 128", book_id=19),
        Bible_Chapter(title="Psalms 129", book_id=19),
        Bible_Chapter(title="Psalms 130", book_id=19),
        Bible_Chapter(title="Psalms 131", book_id=19),
        Bible_Chapter(title="Psalms 132", book_id=19),
        Bible_Chapter(title="Psalms 133", book_id=19),
        Bible_Chapter(title="Psalms 134", book_id=19),
        Bible_Chapter(title="Psalms 135", book_id=19),
        Bible_Chapter(title="Psalms 136", book_id=19),
        Bible_Chapter(title="Psalms 137", book_id=19),
        Bible_Chapter(title="Psalms 138", book_id=19),
        Bible_Chapter(title="Psalms 139", book_id=19),
        Bible_Chapter(title="Psalms 140", book_id=19),
        Bible_Chapter(title="Psalms 141", book_id=19),
        Bible_Chapter(title="Psalms 142", book_id=19),
        Bible_Chapter(title="Psalms 143", book_id=19),
        Bible_Chapter(title="Psalms 144", book_id=19),
        Bible_Chapter(title="Psalms 145", book_id=19),
        Bible_Chapter(title="Psalms 146", book_id=19),
        Bible_Chapter(title="Psalms 147", book_id=19),
        Bible_Chapter(title="Psalms 148", book_id=19),
        Bible_Chapter(title="Psalms 149", book_id=19),
        Bible_Chapter(title="Psalms 150", book_id=19),
        Bible_Chapter(title="Proverbs 1", book_id=20),
        Bible_Chapter(title="Proverbs 2", book_id=20),
        Bible_Chapter(title="Proverbs 3", book_id=20),
        Bible_Chapter(title="Proverbs 4", book_id=20),
        Bible_Chapter(title="Proverbs 5", book_id=20),
        Bible_Chapter(title="Proverbs 6", book_id=20),
        Bible_Chapter(title="Proverbs 7", book_id=20),
        Bible_Chapter(title="Proverbs 8", book_id=20),
        Bible_Chapter(title="Proverbs 9", book_id=20),
        Bible_Chapter(title="Proverbs 10", book_id=20),
        Bible_Chapter(title="Proverbs 11", book_id=20),
        Bible_Chapter(title="Proverbs 12", book_id=20),
        Bible_Chapter(title="Proverbs 13", book_id=20),
        Bible_Chapter(title="Proverbs 14", book_id=20),
        Bible_Chapter(title="Proverbs 15", book_id=20),
        Bible_Chapter(title="Proverbs 16", book_id=20),
        Bible_Chapter(title="Proverbs 17", book_id=20),
        Bible_Chapter(title="Proverbs 18", book_id=20),
        Bible_Chapter(title="Proverbs 19", book_id=20),
        Bible_Chapter(title="Proverbs 20", book_id=20),
        Bible_Chapter(title="Proverbs 21", book_id=20),
        Bible_Chapter(title="Proverbs 22", book_id=20),
        Bible_Chapter(title="Proverbs 23", book_id=20),
        Bible_Chapter(title="Proverbs 24", book_id=20),
        Bible_Chapter(title="Proverbs 25", book_id=20),
        Bible_Chapter(title="Proverbs 26", book_id=20),
        Bible_Chapter(title="Proverbs 27", book_id=20),
        Bible_Chapter(title="Proverbs 28", book_id=20),
        Bible_Chapter(title="Proverbs 29", book_id=20),
        Bible_Chapter(title="Proverbs 30", book_id=20),
        Bible_Chapter(title="Proverbs 31", book_id=20),
        Bible_Chapter(title="Ecclesiastes 1", book_id=21),
        Bible_Chapter(title="Ecclesiastes 2", book_id=21),
        Bible_Chapter(title="Ecclesiastes 3", book_id=21),
        Bible_Chapter(title="Ecclesiastes 4", book_id=21),
        Bible_Chapter(title="Ecclesiastes 5", book_id=21),
        Bible_Chapter(title="Ecclesiastes 6", book_id=21),
        Bible_Chapter(title="Ecclesiastes 7", book_id=21),
        Bible_Chapter(title="Ecclesiastes 8", book_id=21),
        Bible_Chapter(title="Ecclesiastes 9", book_id=21),
        Bible_Chapter(title="Ecclesiastes 10", book_id=21),
        Bible_Chapter(title="Ecclesiastes 11", book_id=21),
        Bible_Chapter(title="Ecclesiastes 12", book_id=21),
        Bible_Chapter(title="Song of Solomon 1", book_id=22),
        Bible_Chapter(title="Song of Solomon 2", book_id=22),
        Bible_Chapter(title="Song of Solomon 3", book_id=22),
        Bible_Chapter(title="Song of Solomon 4", book_id=22),
        Bible_Chapter(title="Song of Solomon 5", book_id=22),
        Bible_Chapter(title="Song of Solomon 6", book_id=22),
        Bible_Chapter(title="Song of Solomon 7", book_id=22),
        Bible_Chapter(title="Song of Solomon 8", book_id=22),
        Bible_Chapter(title="Isaiah 1", book_id=23),
        Bible_Chapter(title="Isaiah 2", book_id=23),
        Bible_Chapter(title="Isaiah 3", book_id=23),
        Bible_Chapter(title="Isaiah 4", book_id=23),
        Bible_Chapter(title="Isaiah 5", book_id=23),
        Bible_Chapter(title="Isaiah 6", book_id=23),
        Bible_Chapter(title="Isaiah 7", book_id=23),
        Bible_Chapter(title="Isaiah 8", book_id=23),
        Bible_Chapter(title="Isaiah 9", book_id=23),
        Bible_Chapter(title="Isaiah 10", book_id=23),
        Bible_Chapter(title="Isaiah 11", book_id=23),
        Bible_Chapter(title="Isaiah 12", book_id=23),
        Bible_Chapter(title="Isaiah 13", book_id=23),
        Bible_Chapter(title="Isaiah 14", book_id=23),
        Bible_Chapter(title="Isaiah 15", book_id=23),
        Bible_Chapter(title="Isaiah 16", book_id=23),
        Bible_Chapter(title="Isaiah 17", book_id=23),
        Bible_Chapter(title="Isaiah 18", book_id=23),
        Bible_Chapter(title="Isaiah 19", book_id=23),
        Bible_Chapter(title="Isaiah 20", book_id=23),
        Bible_Chapter(title="Isaiah 21", book_id=23),
        Bible_Chapter(title="Isaiah 22", book_id=23),
        Bible_Chapter(title="Isaiah 23", book_id=23),
        Bible_Chapter(title="Isaiah 24", book_id=23),
        Bible_Chapter(title="Isaiah 25", book_id=23),
        Bible_Chapter(title="Isaiah 26", book_id=23),
        Bible_Chapter(title="Isaiah 27", book_id=23),
        Bible_Chapter(title="Isaiah 28", book_id=23),
        Bible_Chapter(title="Isaiah 29", book_id=23),
        Bible_Chapter(title="Isaiah 30", book_id=23),
        Bible_Chapter(title="Isaiah 31", book_id=23),
        Bible_Chapter(title="Isaiah 32", book_id=23),
        Bible_Chapter(title="Isaiah 33", book_id=23),
        Bible_Chapter(title="Isaiah 34", book_id=23),
        Bible_Chapter(title="Isaiah 35", book_id=23),
        Bible_Chapter(title="Isaiah 36", book_id=23),
        Bible_Chapter(title="Isaiah 37", book_id=23),
        Bible_Chapter(title="Isaiah 38", book_id=23),
        Bible_Chapter(title="Isaiah 39", book_id=23),
        Bible_Chapter(title="Isaiah 40", book_id=23),
        Bible_Chapter(title="Isaiah 41", book_id=23),
        Bible_Chapter(title="Isaiah 42", book_id=23),
        Bible_Chapter(title="Isaiah 43", book_id=23),
        Bible_Chapter(title="Isaiah 44", book_id=23),
        Bible_Chapter(title="Isaiah 45", book_id=23),
        Bible_Chapter(title="Isaiah 46", book_id=23),
        Bible_Chapter(title="Isaiah 47", book_id=23),
        Bible_Chapter(title="Isaiah 48", book_id=23),
        Bible_Chapter(title="Isaiah 49", book_id=23),
        Bible_Chapter(title="Isaiah 50", book_id=23),
        Bible_Chapter(title="Isaiah 51", book_id=23),
        Bible_Chapter(title="Isaiah 52", book_id=23),
        Bible_Chapter(title="Isaiah 53", book_id=23),
        Bible_Chapter(title="Isaiah 54", book_id=23),
        Bible_Chapter(title="Isaiah 55", book_id=23),
        Bible_Chapter(title="Isaiah 56", book_id=23),
        Bible_Chapter(title="Isaiah 57", book_id=23),
        Bible_Chapter(title="Isaiah 58", book_id=23),
        Bible_Chapter(title="Isaiah 59", book_id=23),
        Bible_Chapter(title="Isaiah 60", book_id=23),
        Bible_Chapter(title="Isaiah 61", book_id=23),
        Bible_Chapter(title="Isaiah 62", book_id=23),
        Bible_Chapter(title="Isaiah 63", book_id=23),
        Bible_Chapter(title="Isaiah 64", book_id=23),
        Bible_Chapter(title="Isaiah 65", book_id=23),
        Bible_Chapter(title="Isaiah 66", book_id=23),
        Bible_Chapter(title="Jeremiah 1", book_id=24),
        Bible_Chapter(title="Jeremiah 2", book_id=24),
        Bible_Chapter(title="Jeremiah 3", book_id=24),
        Bible_Chapter(title="Jeremiah 4", book_id=24),
        Bible_Chapter(title="Jeremiah 5", book_id=24),
        Bible_Chapter(title="Jeremiah 6", book_id=24),
        Bible_Chapter(title="Jeremiah 7", book_id=24),
        Bible_Chapter(title="Jeremiah 8", book_id=24),
        Bible_Chapter(title="Jeremiah 9", book_id=24),
        Bible_Chapter(title="Jeremiah 10", book_id=24),
        Bible_Chapter(title="Jeremiah 11", book_id=24),
        Bible_Chapter(title="Jeremiah 12", book_id=24),
        Bible_Chapter(title="Jeremiah 13", book_id=24),
        Bible_Chapter(title="Jeremiah 14", book_id=24),
        Bible_Chapter(title="Jeremiah 15", book_id=24),
        Bible_Chapter(title="Jeremiah 16", book_id=24),
        Bible_Chapter(title="Jeremiah 17", book_id=24),
        Bible_Chapter(title="Jeremiah 18", book_id=24),
        Bible_Chapter(title="Jeremiah 19", book_id=24),
        Bible_Chapter(title="Jeremiah 20", book_id=24),
        Bible_Chapter(title="Jeremiah 21", book_id=24),
        Bible_Chapter(title="Jeremiah 22", book_id=24),
        Bible_Chapter(title="Jeremiah 23", book_id=24),
        Bible_Chapter(title="Jeremiah 24", book_id=24),
        Bible_Chapter(title="Jeremiah 25", book_id=24),
        Bible_Chapter(title="Jeremiah 26", book_id=24),
        Bible_Chapter(title="Jeremiah 27", book_id=24),
        Bible_Chapter(title="Jeremiah 28", book_id=24),
        Bible_Chapter(title="Jeremiah 29", book_id=24),
        Bible_Chapter(title="Jeremiah 30", book_id=24),
        Bible_Chapter(title="Jeremiah 31", book_id=24),
        Bible_Chapter(title="Jeremiah 32", book_id=24),
        Bible_Chapter(title="Jeremiah 33", book_id=24),
        Bible_Chapter(title="Jeremiah 34", book_id=24),
        Bible_Chapter(title="Jeremiah 35", book_id=24),
        Bible_Chapter(title="Jeremiah 36", book_id=24),
        Bible_Chapter(title="Jeremiah 37", book_id=24),
        Bible_Chapter(title="Jeremiah 38", book_id=24),
        Bible_Chapter(title="Jeremiah 39", book_id=24),
        Bible_Chapter(title="Jeremiah 40", book_id=24),
        Bible_Chapter(title="Jeremiah 41", book_id=24),
        Bible_Chapter(title="Jeremiah 42", book_id=24),
        Bible_Chapter(title="Jeremiah 43", book_id=24),
        Bible_Chapter(title="Jeremiah 44", book_id=24),
        Bible_Chapter(title="Jeremiah 45", book_id=24),
        Bible_Chapter(title="Jeremiah 46", book_id=24),
        Bible_Chapter(title="Jeremiah 47", book_id=24),
        Bible_Chapter(title="Jeremiah 48", book_id=24),
        Bible_Chapter(title="Jeremiah 49", book_id=24),
        Bible_Chapter(title="Jeremiah 50", book_id=24),
        Bible_Chapter(title="Jeremiah 51", book_id=24),
        Bible_Chapter(title="Jeremiah 52", book_id=24),
        Bible_Chapter(title="Lamentations 1", book_id=25),
        Bible_Chapter(title="Lamentations 2", book_id=25),
        Bible_Chapter(title="Lamentations 3", book_id=25),
        Bible_Chapter(title="Lamentations 4", book_id=25),
        Bible_Chapter(title="Lamentations 5", book_id=25),
        Bible_Chapter(title="Ezekiel 1", book_id=26),
        Bible_Chapter(title="Ezekiel 2", book_id=26),
        Bible_Chapter(title="Ezekiel 3", book_id=26),
        Bible_Chapter(title="Ezekiel 4", book_id=26),
        Bible_Chapter(title="Ezekiel 5", book_id=26),
        Bible_Chapter(title="Ezekiel 6", book_id=26),
        Bible_Chapter(title="Ezekiel 7", book_id=26),
        Bible_Chapter(title="Ezekiel 8", book_id=26),
        Bible_Chapter(title="Ezekiel 9", book_id=26),
        Bible_Chapter(title="Ezekiel 10", book_id=26),
        Bible_Chapter(title="Ezekiel 11", book_id=26),
        Bible_Chapter(title="Ezekiel 12", book_id=26),
        Bible_Chapter(title="Ezekiel 13", book_id=26),
        Bible_Chapter(title="Ezekiel 14", book_id=26),
        Bible_Chapter(title="Ezekiel 15", book_id=26),
        Bible_Chapter(title="Ezekiel 16", book_id=26),
        Bible_Chapter(title="Ezekiel 17", book_id=26),
        Bible_Chapter(title="Ezekiel 18", book_id=26),
        Bible_Chapter(title="Ezekiel 19", book_id=26),
        Bible_Chapter(title="Ezekiel 20", book_id=26),
        Bible_Chapter(title="Ezekiel 21", book_id=26),
        Bible_Chapter(title="Ezekiel 22", book_id=26),
        Bible_Chapter(title="Ezekiel 23", book_id=26),
        Bible_Chapter(title="Ezekiel 24", book_id=26),
        Bible_Chapter(title="Ezekiel 25", book_id=26),
        Bible_Chapter(title="Ezekiel 26", book_id=26),
        Bible_Chapter(title="Ezekiel 27", book_id=26),
        Bible_Chapter(title="Ezekiel 28", book_id=26),
        Bible_Chapter(title="Ezekiel 29", book_id=26),
        Bible_Chapter(title="Ezekiel 30", book_id=26),
        Bible_Chapter(title="Ezekiel 31", book_id=26),
        Bible_Chapter(title="Ezekiel 32", book_id=26),
        Bible_Chapter(title="Ezekiel 33", book_id=26),
        Bible_Chapter(title="Ezekiel 34", book_id=26),
        Bible_Chapter(title="Ezekiel 35", book_id=26),
        Bible_Chapter(title="Ezekiel 36", book_id=26),
        Bible_Chapter(title="Ezekiel 37", book_id=26),
        Bible_Chapter(title="Ezekiel 38", book_id=26),
        Bible_Chapter(title="Ezekiel 39", book_id=26),
        Bible_Chapter(title="Ezekiel 40", book_id=26),
        Bible_Chapter(title="Ezekiel 41", book_id=26),
        Bible_Chapter(title="Ezekiel 42", book_id=26),
        Bible_Chapter(title="Ezekiel 43", book_id=26),
        Bible_Chapter(title="Ezekiel 44", book_id=26),
        Bible_Chapter(title="Ezekiel 45", book_id=26),
        Bible_Chapter(title="Ezekiel 46", book_id=26),
        Bible_Chapter(title="Ezekiel 47", book_id=26),
        Bible_Chapter(title="Ezekiel 48", book_id=26),
        Bible_Chapter(title="Daniel 1", book_id=27),
        Bible_Chapter(title="Daniel 2", book_id=27),
        Bible_Chapter(title="Daniel 3", book_id=27),
        Bible_Chapter(title="Daniel 4", book_id=27),
        Bible_Chapter(title="Daniel 5", book_id=27),
        Bible_Chapter(title="Daniel 6", book_id=27),
        Bible_Chapter(title="Daniel 7", book_id=27),
        Bible_Chapter(title="Daniel 8", book_id=27),
        Bible_Chapter(title="Daniel 9", book_id=27),
        Bible_Chapter(title="Daniel 10", book_id=27),
        Bible_Chapter(title="Daniel 11", book_id=27),
        Bible_Chapter(title="Daniel 12", book_id=27),
        Bible_Chapter(title="Hosea 1", book_id=28),
        Bible_Chapter(title="Hosea 2", book_id=28),
        Bible_Chapter(title="Hosea 3", book_id=28),
        Bible_Chapter(title="Hosea 4", book_id=28),
        Bible_Chapter(title="Hosea 5", book_id=28),
        Bible_Chapter(title="Hosea 6", book_id=28),
        Bible_Chapter(title="Hosea 7", book_id=28),
        Bible_Chapter(title="Hosea 8", book_id=28),
        Bible_Chapter(title="Hosea 9", book_id=28),
        Bible_Chapter(title="Hosea 10", book_id=28),
        Bible_Chapter(title="Hosea 11", book_id=28),
        Bible_Chapter(title="Hosea 12", book_id=28),
        Bible_Chapter(title="Hosea 13", book_id=28),
        Bible_Chapter(title="Hosea 14", book_id=28),
        Bible_Chapter(title="Joel 1", book_id=29),
        Bible_Chapter(title="Joel 2", book_id=29),
        Bible_Chapter(title="Joel 3", book_id=29),
        Bible_Chapter(title="Amos 1", book_id=30),
        Bible_Chapter(title="Amos 2", book_id=30),
        Bible_Chapter(title="Amos 3", book_id=30),
        Bible_Chapter(title="Amos 4", book_id=30),
        Bible_Chapter(title="Amos 5", book_id=30),
        Bible_Chapter(title="Amos 6", book_id=30),
        Bible_Chapter(title="Amos 7", book_id=30),
        Bible_Chapter(title="Amos 8", book_id=30),
        Bible_Chapter(title="Amos 9", book_id=30),
        Bible_Chapter(title="Obadiah 1", book_id=31),
        Bible_Chapter(title="Jonah 1", book_id=32),
        Bible_Chapter(title="Jonah 2", book_id=32),
        Bible_Chapter(title="Jonah 3", book_id=32),
        Bible_Chapter(title="Jonah 4", book_id=32),
        Bible_Chapter(title="Micah 1", book_id=33),
        Bible_Chapter(title="Micah 2", book_id=33),
        Bible_Chapter(title="Micah 3", book_id=33),
        Bible_Chapter(title="Micah 4", book_id=33),
        Bible_Chapter(title="Micah 5", book_id=33),
        Bible_Chapter(title="Micah 6", book_id=33),
        Bible_Chapter(title="Micah 7", book_id=33),
        Bible_Chapter(title="Nahum 1", book_id=34),
        Bible_Chapter(title="Nahum 2", book_id=34),
        Bible_Chapter(title="Nahum 3", book_id=34),
        Bible_Chapter(title="Habakkuk 1", book_id=35),
        Bible_Chapter(title="Habakkuk 2", book_id=35),
        Bible_Chapter(title="Habakkuk 3", book_id=35),
        Bible_Chapter(title="Zephaniah 1", book_id=36),
        Bible_Chapter(title="Zephaniah 2", book_id=36),
        Bible_Chapter(title="Zephaniah 3", book_id=36),
        Bible_Chapter(title="Haggai 1", book_id=37),
        Bible_Chapter(title="Haggai 2", book_id=37),
        Bible_Chapter(title="Zechariah 1", book_id=38),
        Bible_Chapter(title="Zechariah 2", book_id=38),
        Bible_Chapter(title="Zechariah 3", book_id=38),
        Bible_Chapter(title="Zechariah 4", book_id=38),
        Bible_Chapter(title="Zechariah 5", book_id=38),
        Bible_Chapter(title="Zechariah 6", book_id=38),
        Bible_Chapter(title="Zechariah 7", book_id=38),
        Bible_Chapter(title="Zechariah 8", book_id=38),
        Bible_Chapter(title="Zechariah 9", book_id=38),
        Bible_Chapter(title="Zechariah 10", book_id=38),
        Bible_Chapter(title="Zechariah 11", book_id=38),
        Bible_Chapter(title="Zechariah 12", book_id=38),
        Bible_Chapter(title="Zechariah 13", book_id=38),
        Bible_Chapter(title="Zechariah 14", book_id=38),
        Bible_Chapter(title="Malachi 1", book_id=39),
        Bible_Chapter(title="Malachi 2", book_id=39),
        Bible_Chapter(title="Malachi 3", book_id=39),
        Bible_Chapter(title="Malachi 4", book_id=39),
        Bible_Chapter(title="Matthew 1", book_id=40),
        Bible_Chapter(title="Matthew 2", book_id=40),
        Bible_Chapter(title="Matthew 3", book_id=40),
        Bible_Chapter(title="Matthew 4", book_id=40),
        Bible_Chapter(title="Matthew 5", book_id=40),
        Bible_Chapter(title="Matthew 6", book_id=40),
        Bible_Chapter(title="Matthew 7", book_id=40),
        Bible_Chapter(title="Matthew 8", book_id=40),
        Bible_Chapter(title="Matthew 9", book_id=40),
        Bible_Chapter(title="Matthew 10", book_id=40),
        Bible_Chapter(title="Matthew 11", book_id=40),
        Bible_Chapter(title="Matthew 12", book_id=40),
        Bible_Chapter(title="Matthew 13", book_id=40),
        Bible_Chapter(title="Matthew 14", book_id=40),
        Bible_Chapter(title="Matthew 15", book_id=40),
        Bible_Chapter(title="Matthew 16", book_id=40),
        Bible_Chapter(title="Matthew 17", book_id=40),
        Bible_Chapter(title="Matthew 18", book_id=40),
        Bible_Chapter(title="Matthew 19", book_id=40),
        Bible_Chapter(title="Matthew 20", book_id=40),
        Bible_Chapter(title="Matthew 21", book_id=40),
        Bible_Chapter(title="Matthew 22", book_id=40),
        Bible_Chapter(title="Matthew 23", book_id=40),
        Bible_Chapter(title="Matthew 24", book_id=40),
        Bible_Chapter(title="Matthew 25", book_id=40),
        Bible_Chapter(title="Matthew 26", book_id=40),
        Bible_Chapter(title="Matthew 27", book_id=40),
        Bible_Chapter(title="Matthew 28", book_id=40),
        Bible_Chapter(title="Mark 1", book_id=41),
        Bible_Chapter(title="Mark 2", book_id=41),
        Bible_Chapter(title="Mark 3", book_id=41),
        Bible_Chapter(title="Mark 4", book_id=41),
        Bible_Chapter(title="Mark 5", book_id=41),
        Bible_Chapter(title="Mark 6", book_id=41),
        Bible_Chapter(title="Mark 7", book_id=41),
        Bible_Chapter(title="Mark 8", book_id=41),
        Bible_Chapter(title="Mark 9", book_id=41),
        Bible_Chapter(title="Mark 10", book_id=41),
        Bible_Chapter(title="Mark 11", book_id=41),
        Bible_Chapter(title="Mark 12", book_id=41),
        Bible_Chapter(title="Mark 13", book_id=41),
        Bible_Chapter(title="Mark 14", book_id=41),
        Bible_Chapter(title="Mark 15", book_id=41),
        Bible_Chapter(title="Mark 16", book_id=41),
        Bible_Chapter(title="Luke 1", book_id=42),
        Bible_Chapter(title="Luke 2", book_id=42),
        Bible_Chapter(title="Luke 3", book_id=42),
        Bible_Chapter(title="Luke 4", book_id=42),
        Bible_Chapter(title="Luke 5", book_id=42),
        Bible_Chapter(title="Luke 6", book_id=42),
        Bible_Chapter(title="Luke 7", book_id=42),
        Bible_Chapter(title="Luke 8", book_id=42),
        Bible_Chapter(title="Luke 9", book_id=42),
        Bible_Chapter(title="Luke 10", book_id=42),
        Bible_Chapter(title="Luke 11", book_id=42),
        Bible_Chapter(title="Luke 12", book_id=42),
        Bible_Chapter(title="Luke 13", book_id=42),
        Bible_Chapter(title="Luke 14", book_id=42),
        Bible_Chapter(title="Luke 15", book_id=42),
        Bible_Chapter(title="Luke 16", book_id=42),
        Bible_Chapter(title="Luke 17", book_id=42),
        Bible_Chapter(title="Luke 18", book_id=42),
        Bible_Chapter(title="Luke 19", book_id=42),
        Bible_Chapter(title="Luke 20", book_id=42),
        Bible_Chapter(title="Luke 21", book_id=42),
        Bible_Chapter(title="Luke 22", book_id=42),
        Bible_Chapter(title="Luke 23", book_id=42),
        Bible_Chapter(title="Luke 24", book_id=42),
        Bible_Chapter(title="John 1", book_id=43),
        Bible_Chapter(title="John 2", book_id=43),
        Bible_Chapter(title="John 3", book_id=43),
        Bible_Chapter(title="John 4", book_id=43),
        Bible_Chapter(title="John 5", book_id=43),
        Bible_Chapter(title="John 6", book_id=43),
        Bible_Chapter(title="John 7", book_id=43),
        Bible_Chapter(title="John 8", book_id=43),
        Bible_Chapter(title="John 9", book_id=43),
        Bible_Chapter(title="John 10", book_id=43),
        Bible_Chapter(title="John 11", book_id=43),
        Bible_Chapter(title="John 12", book_id=43),
        Bible_Chapter(title="John 13", book_id=43),
        Bible_Chapter(title="John 14", book_id=43),
        Bible_Chapter(title="John 15", book_id=43),
        Bible_Chapter(title="John 16", book_id=43),
        Bible_Chapter(title="John 17", book_id=43),
        Bible_Chapter(title="John 18", book_id=43),
        Bible_Chapter(title="John 19", book_id=43),
        Bible_Chapter(title="John 20", book_id=43),
        Bible_Chapter(title="John 21", book_id=43),
        Bible_Chapter(title="Acts 1", book_id=44),
        Bible_Chapter(title="Acts 2", book_id=44),
        Bible_Chapter(title="Acts 3", book_id=44),
        Bible_Chapter(title="Acts 4", book_id=44),
        Bible_Chapter(title="Acts 5", book_id=44),
        Bible_Chapter(title="Acts 6", book_id=44),
        Bible_Chapter(title="Acts 7", book_id=44),
        Bible_Chapter(title="Acts 8", book_id=44),
        Bible_Chapter(title="Acts 9", book_id=44),
        Bible_Chapter(title="Acts 10", book_id=44),
        Bible_Chapter(title="Acts 11", book_id=44),
        Bible_Chapter(title="Acts 12", book_id=44),
        Bible_Chapter(title="Acts 13", book_id=44),
        Bible_Chapter(title="Acts 14", book_id=44),
        Bible_Chapter(title="Acts 15", book_id=44),
        Bible_Chapter(title="Acts 16", book_id=44),
        Bible_Chapter(title="Acts 17", book_id=44),
        Bible_Chapter(title="Acts 18", book_id=44),
        Bible_Chapter(title="Acts 19", book_id=44),
        Bible_Chapter(title="Acts 20", book_id=44),
        Bible_Chapter(title="Acts 21", book_id=44),
        Bible_Chapter(title="Acts 22", book_id=44),
        Bible_Chapter(title="Acts 23", book_id=44),
        Bible_Chapter(title="Acts 24", book_id=44),
        Bible_Chapter(title="Acts 25", book_id=44),
        Bible_Chapter(title="Acts 26", book_id=44),
        Bible_Chapter(title="Acts 27", book_id=44),
        Bible_Chapter(title="Acts 28", book_id=44),
        Bible_Chapter(title="Romans 1", book_id=45),
        Bible_Chapter(title="Romans 2", book_id=45),
        Bible_Chapter(title="Romans 3", book_id=45),
        Bible_Chapter(title="Romans 4", book_id=45),
        Bible_Chapter(title="Romans 5", book_id=45),
        Bible_Chapter(title="Romans 6", book_id=45),
        Bible_Chapter(title="Romans 7", book_id=45),
        Bible_Chapter(title="Romans 8", book_id=45),
        Bible_Chapter(title="Romans 9", book_id=45),
        Bible_Chapter(title="Romans 10", book_id=45),
        Bible_Chapter(title="Romans 11", book_id=45),
        Bible_Chapter(title="Romans 12", book_id=45),
        Bible_Chapter(title="Romans 13", book_id=45),
        Bible_Chapter(title="Romans 14", book_id=45),
        Bible_Chapter(title="Romans 15", book_id=45),
        Bible_Chapter(title="Romans 16", book_id=45),
        Bible_Chapter(title="1 Corinthians 1", book_id=46),
        Bible_Chapter(title="1 Corinthians 2", book_id=46),
        Bible_Chapter(title="1 Corinthians 3", book_id=46),
        Bible_Chapter(title="1 Corinthians 4", book_id=46),
        Bible_Chapter(title="1 Corinthians 5", book_id=46),
        Bible_Chapter(title="1 Corinthians 6", book_id=46),
        Bible_Chapter(title="1 Corinthians 7", book_id=46),
        Bible_Chapter(title="1 Corinthians 8", book_id=46),
        Bible_Chapter(title="1 Corinthians 9", book_id=46),
        Bible_Chapter(title="1 Corinthians 10", book_id=46),
        Bible_Chapter(title="1 Corinthians 11", book_id=46),
        Bible_Chapter(title="1 Corinthians 12", book_id=46),
        Bible_Chapter(title="1 Corinthians 13", book_id=46),
        Bible_Chapter(title="1 Corinthians 14", book_id=46),
        Bible_Chapter(title="1 Corinthians 15", book_id=46),
        Bible_Chapter(title="1 Corinthians 16", book_id=46),
        Bible_Chapter(title="2 Corinthians 1", book_id=47),
        Bible_Chapter(title="2 Corinthians 2", book_id=47),
        Bible_Chapter(title="2 Corinthians 3", book_id=47),
        Bible_Chapter(title="2 Corinthians 4", book_id=47),
        Bible_Chapter(title="2 Corinthians 5", book_id=47),
        Bible_Chapter(title="2 Corinthians 6", book_id=47),
        Bible_Chapter(title="2 Corinthians 7", book_id=47),
        Bible_Chapter(title="2 Corinthians 8", book_id=47),
        Bible_Chapter(title="2 Corinthians 9", book_id=47),
        Bible_Chapter(title="2 Corinthians 10", book_id=47),
        Bible_Chapter(title="2 Corinthians 11", book_id=47),
        Bible_Chapter(title="2 Corinthians 12", book_id=47),
        Bible_Chapter(title="2 Corinthians 13", book_id=47),
        Bible_Chapter(title="Galatians 1", book_id=48),
        Bible_Chapter(title="Galatians 2", book_id=48),
        Bible_Chapter(title="Galatians 3", book_id=48),
        Bible_Chapter(title="Galatians 4", book_id=48),
        Bible_Chapter(title="Galatians 5", book_id=48),
        Bible_Chapter(title="Galatians 6", book_id=48),
        Bible_Chapter(title="Ephesians 1", book_id=49),
        Bible_Chapter(title="Ephesians 2", book_id=49),
        Bible_Chapter(title="Ephesians 3", book_id=49),
        Bible_Chapter(title="Ephesians 4", book_id=49),
        Bible_Chapter(title="Ephesians 5", book_id=49),
        Bible_Chapter(title="Ephesians 6", book_id=49),
        Bible_Chapter(title="Philippians 1", book_id=50),
        Bible_Chapter(title="Philippians 2", book_id=50),
        Bible_Chapter(title="Philippians 3", book_id=50),
        Bible_Chapter(title="Philippians 4", book_id=50),
        Bible_Chapter(title="Colossians 1", book_id=51),
        Bible_Chapter(title="Colossians 2", book_id=51),
        Bible_Chapter(title="Colossians 3", book_id=51),
        Bible_Chapter(title="Colossians 4", book_id=51),
        Bible_Chapter(title="1 Thessalonians 1", book_id=52),
        Bible_Chapter(title="1 Thessalonians 2", book_id=52),
        Bible_Chapter(title="1 Thessalonians 3", book_id=52),
        Bible_Chapter(title="1 Thessalonians 4", book_id=52),
        Bible_Chapter(title="1 Thessalonians 5", book_id=52),
        Bible_Chapter(title="2 Thessalonians 1", book_id=53),
        Bible_Chapter(title="2 Thessalonians 2", book_id=53),
        Bible_Chapter(title="2 Thessalonians 3", book_id=53),
        Bible_Chapter(title="1 Timothy 1", book_id=54),
        Bible_Chapter(title="1 Timothy 2", book_id=54),
        Bible_Chapter(title="1 Timothy 3", book_id=54),
        Bible_Chapter(title="1 Timothy 4", book_id=54),
        Bible_Chapter(title="1 Timothy 5", book_id=54),
        Bible_Chapter(title="1 Timothy 6", book_id=54),
        Bible_Chapter(title="2 Timothy 1", book_id=55),
        Bible_Chapter(title="2 Timothy 2", book_id=55),
        Bible_Chapter(title="2 Timothy 3", book_id=55),
        Bible_Chapter(title="2 Timothy 4", book_id=55),
        Bible_Chapter(title="Titus 1", book_id=56),
        Bible_Chapter(title="Titus 2", book_id=56),
        Bible_Chapter(title="Titus 3", book_id=56),
        Bible_Chapter(title="Philemon 1", book_id=57),
        Bible_Chapter(title="Hebrews 1", book_id=58),
        Bible_Chapter(title="Hebrews 2", book_id=58),
        Bible_Chapter(title="Hebrews 3", book_id=58),
        Bible_Chapter(title="Hebrews 4", book_id=58),
        Bible_Chapter(title="Hebrews 5", book_id=58),
        Bible_Chapter(title="Hebrews 6", book_id=58),
        Bible_Chapter(title="Hebrews 7", book_id=58),
        Bible_Chapter(title="Hebrews 8", book_id=58),
        Bible_Chapter(title="Hebrews 9", book_id=58),
        Bible_Chapter(title="Hebrews 10", book_id=58),
        Bible_Chapter(title="Hebrews 11", book_id=58),
        Bible_Chapter(title="Hebrews 12", book_id=58),
        Bible_Chapter(title="Hebrews 13", book_id=58),
        Bible_Chapter(title="James 1", book_id=59),
        Bible_Chapter(title="James 2", book_id=59),
        Bible_Chapter(title="James 3", book_id=59),
        Bible_Chapter(title="James 4", book_id=59),
        Bible_Chapter(title="James 5", book_id=59),
        Bible_Chapter(title="1 Peter 1", book_id=60),
        Bible_Chapter(title="1 Peter 2", book_id=60),
        Bible_Chapter(title="1 Peter 3", book_id=60),
        Bible_Chapter(title="1 Peter 4", book_id=60),
        Bible_Chapter(title="1 Peter 5", book_id=60),
        Bible_Chapter(title="2 Peter 1", book_id=61),
        Bible_Chapter(title="2 Peter 2", book_id=61),
        Bible_Chapter(title="2 Peter 3", book_id=61),
        Bible_Chapter(title="1 John 1", book_id=62),
        Bible_Chapter(title="1 John 2", book_id=62),
        Bible_Chapter(title="1 John 3", book_id=62),
        Bible_Chapter(title="1 John 4", book_id=62),
        Bible_Chapter(title="1 John 5", book_id=62),
        Bible_Chapter(title="2 John 1", book_id=63),
        Bible_Chapter(title="3 John 1", book_id=64),
        Bible_Chapter(title="Jude 1", book_id=65),
        Bible_Chapter(title="Revelation 1", book_id=66),
        Bible_Chapter(title="Revelation 2", book_id=66),
        Bible_Chapter(title="Revelation 3", book_id=66),
        Bible_Chapter(title="Revelation 4", book_id=66),
        Bible_Chapter(title="Revelation 5", book_id=66),
        Bible_Chapter(title="Revelation 6", book_id=66),
        Bible_Chapter(title="Revelation 7", book_id=66),
        Bible_Chapter(title="Revelation 8", book_id=66),
        Bible_Chapter(title="Revelation 9", book_id=66),
        Bible_Chapter(title="Revelation 10", book_id=66),
        Bible_Chapter(title="Revelation 11", book_id=66),
        Bible_Chapter(title="Revelation 12", book_id=66),
        Bible_Chapter(title="Revelation 13", book_id=66),
        Bible_Chapter(title="Revelation 14", book_id=66),
        Bible_Chapter(title="Revelation 15", book_id=66),
        Bible_Chapter(title="Revelation 16", book_id=66),
        Bible_Chapter(title="Revelation 17", book_id=66),
        Bible_Chapter(title="Revelation 18", book_id=66),
        Bible_Chapter(title="Revelation 19", book_id=66),
        Bible_Chapter(title="Revelation 20", book_id=66),
        Bible_Chapter(title="Revelation 21", book_id=66),
        Bible_Chapter(title="Revelation 22", book_id=66)
    ]

    try:

        db.bulk_save_objects(chapters)
        db.commit()

        logging.info("Creating chapters of the bible")

    except:
        logging.error('NOT WORKING')


def main() -> None:
    logger.info("Initializing service")
    init()
    create_books(db=SessionLocal())
    create_chapter(db=SessionLocal())
    logger.info("Service finished initializing")


if __name__ == "__main__":
    main()
