"""updated

Revision ID: 213d08cf4ef5
Revises: fb6f04790487
Create Date: 2021-11-17 07:14:36.135750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213d08cf4ef5'
down_revision = 'fb6f04790487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bible_chapter_title'),
                    'bible_chapter', ['title'], unique=False)
    op.add_column('bible_verse', sa.Column('chapter', sa.String(), nullable=True))
    op.drop_index('ix_bible_verse_book_id', table_name='bible_verse')
    op.drop_constraint('bible_verse_book_id_fkey', 'bible_verse', type_='foreignkey')
    op.drop_column('bible_verse', 'book_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bible_verse', sa.Column(
        'book_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bible_verse', type_='foreignkey')
    op.create_foreign_key('bible_verse_book_id_fkey', 'bible_verse',
                          'bible_book', ['book_id'], ['id'])
    op.drop_index(op.f('ix_bible_verse_chapter'), table_name='bible_verse')
    op.create_index('ix_bible_verse_book_id', 'bible_verse', ['book_id'], unique=False)
    op.drop_column('bible_verse', 'chapter')
    op.drop_index(op.f('ix_bible_chapter_title'), table_name='bible_chapter')
    # ### end Alembic commands ###
