"""auto fill modified_at column

Revision ID: 2790ffda5982
Revises: 8267f00b3b4c
Create Date: 2021-11-03 06:01:21.721151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2790ffda5982'
down_revision = '8267f00b3b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
