"""bible chapter not unique

Revision ID: 314a0cbb454e
Revises: ac77c00b2549
Create Date: 2021-11-05 09:47:38.024234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314a0cbb454e'
down_revision = 'ac77c00b2549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bible_chapter_title_key', 'bible_chapter', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('bible_chapter_title_key', 'bible_chapter', ['title'])
    # ### end Alembic commands ###
