"""verse model modified

Revision ID: 90e89745a8fe
Revises: a7bd865817ac
Create Date: 2021-11-17 05:51:09.850940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e89745a8fe'
down_revision = 'a7bd865817ac'
branch_labels = None
depends_on = None


def upgrade():
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
