"""user model extended

Revision ID: 8267f00b3b4c
Revises: d4867f3a4c0a
Create Date: 2021-11-01 22:14:09.348615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8267f00b3b4c"
down_revision = "d4867f3a4c0a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("first_name", sa.String(), nullable=False))
    op.add_column("user", sa.Column("last_name", sa.String(), nullable=False))
    op.add_column("user", sa.Column("phone_number", sa.String(), nullable=False))
    op.add_column("user", sa.Column("date_of_birth", sa.Date(), nullable=True))
    op.add_column("user", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("user", sa.Column("modified_at", sa.DateTime(), nullable=True))
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.create_index(op.f("ix_user_phone_number"), "user", ["phone_number"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_phone_number"), table_name="user")
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("user", "modified_at")
    op.drop_column("user", "created_at")
    op.drop_column("user", "date_of_birth")
    op.drop_column("user", "phone_number")
    op.drop_column("user", "last_name")
    op.drop_column("user", "first_name")
    # ### end Alembic commands ###
