"""migration for bible books


Revision ID: 883c4af2c331
Revises: bc83f3380051
Create Date: 2021-11-16 23:42:08.710472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Table, MetaData


# revision identifiers, used by Alembic.
revision = '883c4af2c331'
down_revision = 'bc83f3380051'
branch_labels = None
depends_on = None


def upgrade():

    meta = MetaData(bind=op.get_bind())

    # pass in tuple with tables we want to reflect, otherwise whole database will get reflected
    meta.reflect(only=('bible_book',))

    # define table representation
    bible_book_tbl = Table('bible_book', meta)

    # insert records
    op.bulk_insert(
        bible_book_tbl,
        [
            {"title": "Genesis", "slug": "GEN"}, {"title": "Exodus", "slug": "EXO"}, {"title": "Leviticus", "slug": "LEV"}, {"title": "Numbers", "slug": "NUM"}, {"title": "Deuteronomy", "slug": "DEU"}, {"title": "Joshua", "slug": "JOS"}, {"title": "Judges", "slug": "JDG"}, {"title": "Ruth", "slug": "RUT"}, {"title": "1 Samuel", "slug": "1SA"}, {"title": "2 Samuel", "slug": "2SA"}, {"title": "1 Kings", "slug": "1KI"}, {"title": "2 Kings", "slug": "2KI"}, {"title": "1 Chronicles", "slug": "1CH"}, {"title": "2 Chronicles", "slug": "2CH"}, {"title": "Ezra", "slug": "EZR"}, {"title": "Nehemiah", "slug": "NEH"}, {"title": "Esther", "slug": "EST"}, {"title": "Job", "slug": "JOB"}, {"title": "Psalms", "slug": "PSA"}, {"title": "Proverbs", "slug": "PRO"}, {"title": "Ecclesiastes", "slug": "ECC"}, {"title": "Song of Solomon", "slug": "SNG"}, {"title": "Isaiah", "slug": "ISA"}, {"title": "Jeremiah", "slug": "JER"}, {"title": "Lamentations", "slug": "LAM"}, {"title": "Ezekiel", "slug": "EZK"}, {"title": "Daniel", "slug": "DAN"}, {"title": "Hosea", "slug": "HOS"}, {"title": "Joel", "slug": "JOL"}, {"title": "Amos", "slug": "AMO"}, {"title": "Obadiah", "slug": "OBA"}, {"title": "Jonah", "slug": "JON"}, {"title": "Micah", "slug": "MIC"}, {"title": "Nahum", "slug": "NAM"}, {"title": "Habakkuk", "slug": "HAB"}, {"title": "Zephaniah", "slug": "ZEP"}, {"title": "Haggai", "slug": "HAG"}, {"title": "Zechariah", "slug": "ZEC"}, {"title": "Malachi", "slug": "MAL"}, {"title": "Matthew", "slug": "MAT"}, {"title": "Mark", "slug": "MRK"}, {"title": "Luke", "slug": "LUK"}, {"title": "John", "slug": "JHN"}, {"title": "Acts", "slug": "ACT"}, {"title": "Romans", "slug": "ROM"}, {"title": "1 Corinthians", "slug": "1CO"}, {"title": "2 Corinthians", "slug": "2CO"}, {"title": "Galatians", "slug": "GAL"}, {"title": "Ephesians", "slug": "EPH"}, {"title": "Philippians", "slug": "PHP"}, {"title": "Colossians", "slug": "COL"}, {"title": "1 Thessalonians", "slug": "1TH"}, {"title": "2 Thessalonians", "slug": "2TH"}, {"title": "1 Timothy", "slug": "1TI"}, {"title": "2 Timothy", "slug": "2TI"}, {"title": "Titus", "slug": "TIT"}, {"title": "Philemon", "slug": "PHM"}, {"title": "Hebrews", "slug": "HEB"}, {"title": "James", "slug": "JAS"}, {"title": "1 Peter", "slug": "1PE"}, {"title": "2 Peter", "slug": "2PE"}, {"title": "1 John", "slug": "1JN"}, {"title": "2 John", "slug": "2JN"}, {"title": "3 John", "slug": "3JN"}, {"title": "Jude", "slug": "JUD"}, {"title": "Revelation", "slug": "REV"}]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
