"""bible book and chapter added

Revision ID: ac77c00b2549
Revises: 2790ffda5982
Create Date: 2021-11-04 04:57:01.629719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac77c00b2549'
down_revision = '2790ffda5982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bible_book',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('slug', sa.String(), nullable=True),
                    sa.Column('chapter_count', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('slug'),
                    sa.UniqueConstraint('title')
                    )
    op.create_index(op.f('ix_bible_book_id'), 'bible_book', ['id'], unique=False)
    op.create_table('bible_chapter',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('book_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['book_id'], ['bible_book.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('title')
                    )
    op.create_index(op.f('ix_bible_chapter_id'), 'bible_chapter', ['id'], unique=False)
    op.drop_index('ix_item_description', table_name='item')
    op.drop_index('ix_item_id', table_name='item')
    op.drop_index('ix_item_title', table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('title', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('description', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('owner_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(
                        ['owner_id'], ['user.id'], name='item_owner_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='item_pkey')
                    )
    op.create_index('ix_item_title', 'item', ['title'], unique=False)
    op.create_index('ix_item_id', 'item', ['id'], unique=False)
    op.create_index('ix_item_description', 'item', ['description'], unique=False)
    op.drop_index(op.f('ix_bible_chapter_id'), table_name='bible_chapter')
    op.drop_table('bible_chapter')
    op.drop_index(op.f('ix_bible_book_id'), table_name='bible_book')
    op.drop_table('bible_book')
    # ### end Alembic commands ###
